version: '3.8'

services:
  kafka:
    container_name: kafka-t2
    image: bashj79/kafka-kraft
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/opt/kafka/kafka-logs
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-t2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev
    volumes:
      - .:/opt/jboss/keycloak/imports

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin-t1
    ports:
      - "9411:9411"

  prometheus:
    image: prom/prometheus
    container_name: prometheus-t1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana-t1
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_config:/etc/grafana
    networks:
      - monitor-net


  mongodb:
    container_name: turkcell2-filterdb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  invoicedb:
    container_name: invoicedb
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - invoicedb_data:/data/db

  paymentdb:
    container_name: paymentdb-t2
    image: mysql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_TCP_PORT=3307
      - VIRTUAL_PORT=3307
    volumes:
      - paymentdb_data:/data/db

volumes:
  grafana_data:
  grafana_config:
  kafka_data:
  mongodb_data:
  invoicedb_data:
  paymentdb_data:

networks:
  monitor-net:
    driver: bridge